@echo off

echo Starting product-service...
start "product-service" cmd /k "cd /d product-service && mvn spring-boot:run"

echo Starting auth-service...
start "auth-service" cmd /k "cd /d auth-service && mvn spring-boot:run"

echo Starting api-gateway...
start "api-gateway" cmd /k "cd /d api-gateway && mvn spring-boot:run"

echo Starting order-service...
start "order-service" cmd /k "cd /d order-service && mvn spring-boot:run"

echo Starting inventory-service...
start "inventory-service" cmd /k "cd /d inventory-service && mvn spring-boot:run"

echo Starting inventory-service...
start "payment-service" cmd /k "cd /d payment-service && mvn spring-boot:run"

echo Starting frontend ...
start "frontend" cmd /k "cd /d ecommerce-frontend && npm run dev"

echo All services are starting...